node{
    def app
        stage('Build'){
                dir("test-jenkins"){
                    sh "mvn clean package -P dev -DskipTests"
                }
        }

        stage('Test'){
                echo "Test are skipped"
        }

        stage('Quality-Gate'){
                echo "Quality Gate are skipped!"
        }

        stage('Build And Push Image'){
            dir("test-jenkins"){
                docker.withRegistry('https://registry.hub.docker.com','docker-hub'){
                    app = docker.build("slanzini/test-jenkins:1.0.0")
                    app.push()
                }
            }
        }

        stage('Deploy') {
            sh 'kubectl scale deployments test-jenkins --replicas=0'
            sh 'kubectl scale deployments test-jenkins --replicas=1'
        }
}