node{
    def app
        stage('Build'){
                echo "Running Build!"
                dir("test-jenkins"){
                    sh "mvn clean install -P dev -DskipTests"
                }
        }

        stage('Test'){
                echo "Test are skipped"
        }

        stage('Quality-Gate'){
                echo "Quality Gate are skipped! Test Poll"
        }

        stage('Build And Push Image'){
            dir("test-jenkins"){
                docker.withRegistry('https://registry.hub.docker.com','docker-hub'){
                    app = docker.build("slanzini/test-jenkins:1.0.0")
                    app.push()
                }
            }
        }

        stage('List pods') {
            withKubeCredentials([
                [credentialsId: 'kubectl-udm', serverUrl: 'https://10.206.195.55/', clusterName: 'giottodevk8s', namespace: 'udm'],
            ]) {
              sh 'kubectl get pods'
            }
        }
}