pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                echo "Running Build!"
                dir("test-jenkins"){
                    bat "mvn clean install -DskipTests"
                }
            }
        }

        stage('Test'){
            steps{
                echo "Test are Skipped!"
            }
        }

        stage('Quality-Gate'){
            steps{
                echo "Quality Gate are skipped!"
            }
        }

        stage('Deploy'){
            steps{
                echo "Running Deploy!"
                dir("test-jenkins\target"){
                    bat "java -jar test-jenkins-0.0.1-SNAPSHOT.jar"
                }
            }
        }
    }
    post{
        always{
            echo "This will always run"
        }
        success{
            echo "This will run only if succesfull"
        }
        failure{
            echo "This will run only if failed"
        }
        unstable{
            echo "This will run only if the run was marked as unstable"
        }
        changed{
            echo "This will run only if the state of the Pipeline has changed"
        }
    }
}