apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-jenkins
  name: test-jenkins
  namespace: udm
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: test-jenkins
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-jenkins
    spec:
      containers:
      - image: slanzini/test-jenkins:1.0.0
        imagePullPolicy: Always
        name: test-jenkins
        ports:
        - containerPort: 8880
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /test-jenkins-cfg
          name: configurations
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - configMap:
          defaultMode: 420
          name: test-jenkins-cfg
        name: configurations